import Sidebar from '../components/Sidebar';
import '../styles/Expenses.css';

function Expenses({ goPage }) {
  return (
    <div id="expenses-page">
      <Sidebar activePage="expenses" goPage={goPage} />
      <div className="db-main">
        <div className="tb"><span className="tb-title"></span><div className="tb-right"><div className="tb-bell"><svg viewBox="0 0 24 24"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg></div><div className="tb-user"><div className="tb-avatar" style={{ background: 'linear-gradient(135deg,#7c3aed,#a78bfa)' }}>SJ</div><div><div className="tb-uname">Sarah Johns</div><div className="tb-urole">Administrator</div></div></div></div></div>
        <div className="pg">
          <div className="pg-header">
            <div className="pg-header-left"><h1>Expense Management</h1><p>Track employee expenses, manage approvals, and ensure policy compliance</p></div>
            <div className="pg-header-actions">
              <button className="btn-action btn-purple"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>Capture Receipt</button>
              <button className="btn-action btn-blue"><svg viewBox="0 0 24 24"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>Submit Expense</button>
            </div>
          </div>
          <div className="kpi-row" style={{ marginBottom: '20px' }}>
            <div className="kpi"><div className="kpi-label">Pending Approval</div><div className="kpi-body"><div className="kpi-value">$12,450</div><div className="kpi-icon ic-o"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></div></div><div style={{ fontSize: '13px', fontWeight: 500, color: '#d97706', marginTop: '6px' }}>23 submissions</div></div>
            <div className="kpi"><div className="kpi-label">Approved</div><div className="kpi-body"><div className="kpi-value">$38,920</div><div className="kpi-icon ic-g"><svg viewBox="0 0 24 24"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg></div></div><div style={{ fontSize: '13px', fontWeight: 500, color: '#16a34a', marginTop: '6px' }}>This month</div></div>
            <div className="kpi"><div className="kpi-label">To Reimburse</div><div className="kpi-body"><div className="kpi-value">$24,680</div><div className="kpi-icon ic-b"><svg viewBox="0 0 24 24"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg></div></div><div style={{ fontSize: '13px', fontWeight: 500, color: '#2563eb', marginTop: '6px' }}>15 employees</div></div>
            <div className="kpi"><div className="kpi-label">Policy Flags</div><div className="kpi-body"><div className="kpi-value" style={{ color: '#dc2626' }}>7</div><div className="kpi-icon" style={{ background: '#fee2e2', color: '#dc2626', width: '48px', height: '48px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><svg viewBox="0 0 24 24" style={{ width: '24px', height: '24px' }} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg></div></div><div style={{ fontSize: '13px', fontWeight: 500, color: '#dc2626', marginTop: '6px' }}>Requires review</div></div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 280px', gap: '18px', alignItems: 'start' }}>
            <div>
              {/* Recent Submissions */}
              <div style={{ background: '#fff', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,.06)', padding: '22px 24px', marginBottom: '16px' }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '18px' }}>
                  <div style={{ fontSize: '15px', fontWeight: 700, color: '#111827' }}>Recent Submissions</div>
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <select style={{ height: '34px', padding: '0 28px 0 10px', border: '1px solid #e5e7eb', borderRadius: '8px', fontSize: '13px', color: '#374151', background: '#fff', appearance: 'none', cursor: 'pointer' }}><option>All Status</option><option>Pending</option><option>Approved</option><option>Rejected</option></select>
                    <button style={{ height: '34px', padding: '0 12px', border: '1px solid #e5e7eb', borderRadius: '8px', background: '#fff', color: '#374151', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center' }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/></svg></button>
                  </div>
                </div>
                {/* Business Travel - Pending */}
                <div style={{ border: '1px solid #e5e7eb', borderRadius: '10px', padding: '18px', marginBottom: '12px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}><div style={{ width: '36px', height: '36px', borderRadius: '50%', background: 'linear-gradient(135deg,#7c3aed,#a78bfa)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '11px', fontWeight: 700, color: '#fff', flexShrink: 0 }}>JS</div><div><div style={{ fontSize: '14px', fontWeight: 700, color: '#111827' }}>Business Travel - NYC</div><div style={{ fontSize: '12px', color: '#9ca3af' }}>John Smith • Submitted Dec 14</div></div></div><span style={{ background: '#fef9c3', color: '#a16207', fontSize: '12px', fontWeight: 600, padding: '3px 10px', borderRadius: '12px' }}>Pending</span></div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '12px', marginBottom: '14px' }}>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Amount</div><div style={{ fontSize: '14px', fontWeight: 700, color: '#111827' }}>$2,450.00</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Category</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>Travel</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Receipts</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>5 attached</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Project</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>TechCorp</div></div>
                  </div>
                  <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                    <button style={{ flex: 1, height: '36px', background: '#16a34a', color: '#fff', border: 'none', borderRadius: '8px', fontSize: '13.5px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>Approve</button>
                    <button style={{ flex: 1, height: '36px', background: '#dc2626', color: '#fff', border: 'none', borderRadius: '8px', fontSize: '13.5px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>Reject</button>
                    <button style={{ width: '36px', height: '36px', border: '1px solid #e5e7eb', borderRadius: '8px', background: '#fff', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#6b7280" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg></button>
                  </div>
                </div>
                {/* Policy Flag - Client Dinner */}
                <div style={{ border: '1px solid #fecaca', borderRadius: '10px', padding: '18px', background: '#fff5f5', marginBottom: '12px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}><div style={{ width: '36px', height: '36px', borderRadius: '50%', background: 'linear-gradient(135deg,#f59e0b,#ef4444)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '11px', fontWeight: 700, color: '#fff', flexShrink: 0 }}>MJ</div><div><div style={{ fontSize: '14px', fontWeight: 700, color: '#111827' }}>Client Dinner - Restaurant</div><div style={{ fontSize: '12px', color: '#9ca3af' }}>Mike Johnson • Submitted Dec 13</div></div></div><span style={{ background: '#fee2e2', color: '#dc2626', fontSize: '12px', fontWeight: 600, padding: '3px 10px', borderRadius: '12px' }}>Policy Flag</span></div>
                  <div style={{ background: '#fee2e2', borderRadius: '7px', padding: '8px 12px', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12.5px', color: '#dc2626', fontWeight: 500 }}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>Exceeds meal limit by $45. Requires manager override.</div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '12px', marginBottom: '14px' }}>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Amount</div><div style={{ fontSize: '14px', fontWeight: 700, color: '#dc2626' }}>$145.00</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Category</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>Meals</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Receipts</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>1 attached</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Policy Limit</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>$100</div></div>
                  </div>
                  <div style={{ display: 'flex', gap: '10px' }}>
                    <button style={{ flex: 1, height: '36px', background: '#16a34a', color: '#fff', border: 'none', borderRadius: '8px', fontSize: '13.5px', fontWeight: 600, cursor: 'pointer' }}>Override &amp; Approve</button>
                    <button style={{ flex: 1, height: '36px', background: '#dc2626', color: '#fff', border: 'none', borderRadius: '8px', fontSize: '13.5px', fontWeight: 600, cursor: 'pointer' }}>Reject</button>
                  </div>
                </div>
                {/* Office Supplies - Approved */}
                <div style={{ border: '1px solid #e5e7eb', borderRadius: '10px', padding: '18px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}><div style={{ width: '36px', height: '36px', borderRadius: '50%', background: 'linear-gradient(135deg,#16a34a,#10b981)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '11px', fontWeight: 700, color: '#fff', flexShrink: 0 }}>SJ</div><div><div style={{ fontSize: '14px', fontWeight: 700, color: '#111827' }}>Office Supplies</div><div style={{ fontSize: '12px', color: '#9ca3af' }}>Sarah Johnson • Submitted Dec 12</div></div></div><span style={{ background: '#dcfce7', color: '#15803d', fontSize: '12px', fontWeight: 600, padding: '3px 10px', borderRadius: '12px' }}>Approved</span></div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '12px' }}>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Amount</div><div style={{ fontSize: '14px', fontWeight: 700, color: '#111827' }}>$87.50</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Category</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>Supplies</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Receipts</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#111827' }}>2 attached</div></div>
                    <div><div style={{ fontSize: '11.5px', color: '#9ca3af', marginBottom: '2px' }}>Status</div><div style={{ fontSize: '14px', fontWeight: 600, color: '#16a34a' }}>Reimbursed</div></div>
                  </div>
                </div>
              </div>
              {/* Approval Workflow + Reports */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div style={{ background: '#fff', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,.06)', padding: '22px 24px' }}>
                  <div style={{ fontSize: '15px', fontWeight: 700, color: '#111827', marginBottom: '20px' }}>Approval Workflow</div>
                  <div style={{ display: 'flex', gap: '14px', marginBottom: '16px' }}><div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}><div style={{ width: '32px', height: '32px', background: '#16a34a', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg></div><div style={{ width: '2px', flex: 1, background: '#e5e7eb', margin: '6px 0' }}></div></div><div style={{ paddingTop: '4px' }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: '#111827', marginBottom: '2px' }}>Employee Submission</div><div style={{ fontSize: '12.5px', color: '#6b7280', marginBottom: '3px' }}>Expense submitted with receipts and details</div><div style={{ fontSize: '12px', fontWeight: 600, color: '#16a34a' }}>✓ Completed</div></div></div>
                  <div style={{ display: 'flex', gap: '14px', marginBottom: '16px' }}><div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}><div style={{ width: '32px', height: '32px', background: '#7c3aed', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg></div><div style={{ width: '2px', flex: 1, background: '#e5e7eb', margin: '6px 0' }}></div></div><div style={{ paddingTop: '4px' }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: '#111827', marginBottom: '2px' }}>Manager Review</div><div style={{ fontSize: '12.5px', color: '#6b7280', marginBottom: '3px' }}>Policy compliance check and approval</div><div style={{ fontSize: '12px', fontWeight: 600, color: '#7c3aed' }}>⏱ In Progress - 23 pending</div></div></div>
                  <div style={{ display: 'flex', gap: '14px', marginBottom: '16px' }}><div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}><div style={{ width: '32px', height: '32px', background: '#e5e7eb', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#6b7280" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg></div><div style={{ width: '2px', flex: 1, background: '#e5e7eb', margin: '6px 0' }}></div></div><div style={{ paddingTop: '4px' }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: '#111827', marginBottom: '2px' }}>Finance Approval</div><div style={{ fontSize: '12.5px', color: '#6b7280', marginBottom: '3px' }}>Final review and accounting processing</div><div style={{ fontSize: '12px', fontWeight: 500, color: '#6b7280' }}>⏱ In Progress - 12 pending</div></div></div>
                  <div style={{ display: 'flex', gap: '14px' }}><div style={{ width: '32px', height: '32px', background: '#7c3aed', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg></div><div style={{ paddingTop: '4px' }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: '#111827', marginBottom: '2px' }}>Reimbursement</div><div style={{ fontSize: '12.5px', color: '#6b7280', marginBottom: '3px' }}>Payment processing and employee notification</div><div style={{ fontSize: '12px', fontWeight: 600, color: '#7c3aed' }}>✓ Completed</div></div></div>
                </div>
                <div style={{ background: '#fff', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,.06)', padding: '22px 24px' }}>
                  <div style={{ fontSize: '15px', fontWeight: 700, color: '#111827', marginBottom: '16px' }}>Expense Reports</div>
                  <div style={{ border: '1px solid #e5e7eb', borderRadius: '9px', padding: '14px', marginBottom: '10px' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '30px', height: '30px', borderRadius: '50%', background: 'linear-gradient(135deg,#7c3aed,#a78bfa)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '9px', fontWeight: 700, color: '#fff' }}>JS</div><div><div style={{ fontSize: '13px', fontWeight: 600, color: '#111827' }}>Q4 2023 Travel Report</div><div style={{ fontSize: '11.5px', color: '#9ca3af' }}>John Smith • Dec 1-31, 2023</div></div></div><span style={{ background: '#dcfce7', color: '#15803d', fontSize: '11.5px', fontWeight: 600, padding: '2px 8px', borderRadius: '10px' }}>Approved</span></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '8px' }}><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Total Amount</div><div style={{ fontSize: '12.5px', fontWeight: 700, color: '#111827' }}>$12,450.00</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Category</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#111827' }}>Travel</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Receipts</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#111827' }}>23 attached</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Status</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#16a34a' }}>Reimbursed</div></div></div></div>
                  <div style={{ border: '1px solid #fde68a', borderRadius: '9px', padding: '14px', background: '#fffbeb', marginBottom: '10px' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '30px', height: '30px', borderRadius: '50%', background: 'linear-gradient(135deg,#f59e0b,#ef4444)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '9px', fontWeight: 700, color: '#fff' }}>MJ</div><div><div style={{ fontSize: '13px', fontWeight: 600, color: '#111827' }}>Q4 2023 Meals Report</div><div style={{ fontSize: '11.5px', color: '#9ca3af' }}>Mike Johnson • Dec 1-31, 2023</div></div></div><span style={{ background: '#fef9c3', color: '#a16207', fontSize: '11.5px', fontWeight: 600, padding: '2px 8px', borderRadius: '10px' }}>Pending</span></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '8px' }}><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Total Amount</div><div style={{ fontSize: '12.5px', fontWeight: 700, color: '#111827' }}>$1,890.00</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Category</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#111827' }}>Meals</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Receipts</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#111827' }}>12 attached</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Status</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#d97706' }}>Policy Flag</div></div></div></div>
                  <div style={{ border: '1px solid #e5e7eb', borderRadius: '9px', padding: '14px' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '30px', height: '30px', borderRadius: '50%', background: 'linear-gradient(135deg,#16a34a,#10b981)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '9px', fontWeight: 700, color: '#fff' }}>SJ</div><div><div style={{ fontSize: '13px', fontWeight: 600, color: '#111827' }}>Q4 2023 Supplies Report</div><div style={{ fontSize: '11.5px', color: '#9ca3af' }}>Sarah Johnson • Dec 1-31, 2023</div></div></div><span style={{ background: '#dcfce7', color: '#15803d', fontSize: '11.5px', fontWeight: 600, padding: '2px 8px', borderRadius: '10px' }}>Approved</span></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '8px' }}><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Total Amount</div><div style={{ fontSize: '12.5px', fontWeight: 700, color: '#111827' }}>$1,250.00</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Category</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#111827' }}>Supplies</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Receipts</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#111827' }}>8 attached</div></div><div><div style={{ fontSize: '11px', color: '#9ca3af' }}>Status</div><div style={{ fontSize: '12.5px', fontWeight: 600, color: '#16a34a' }}>Reimbursed</div></div></div></div>
                </div>
              </div>
            </div>
            {/* Right sidebar */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <div style={{ background: '#fff', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,.06)', padding: '20px' }}>
                <div style={{ fontSize: '14.5px', fontWeight: 700, color: '#111827', marginBottom: '16px' }}>Category Breakdown</div>
                {[['Travel','$18,450',88,'#7c3aed'],['Meals','$8,920',43,'#16a34a'],['Supplies','$5,680',27,'#a78bfa'],['Software','$4,230',20,'#f59e0b'],['Other','$1,640',8,'#6b7280']].map(([label,val,w,color]) => (
                  <div key={label} style={{ marginBottom: '12px' }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '5px' }}><span style={{ fontSize: '13px', color: '#374151' }}>{label}</span><span style={{ fontSize: '13px', fontWeight: 700, color: '#111827' }}>{val}</span></div><div style={{ height: '6px', background: '#f3f4f6', borderRadius: '3px', overflow: 'hidden' }}><div style={{ width: `${w}%`, height: '100%', background: color, borderRadius: '3px' }}></div></div></div>
                ))}
              </div>
              <div style={{ background: '#fff', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,.06)', padding: '20px' }}>
                <div style={{ fontSize: '14.5px', fontWeight: 700, color: '#111827', marginBottom: '14px' }}>Quick Actions</div>
                {[['Export to Accounting','#2563eb'],['Process Reimbursements','#16a34a'],['Policy Settings','#7c3aed'],['Vendor Matching','#ea580c']].map(([label,color]) => (
                  <div key={label} style={{ padding: '12px 14px', borderRadius: '9px', border: '1px solid #e5e7eb', marginBottom: '8px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer' }}><span style={{ fontSize: '13.5px', fontWeight: 600, color }}>{label}</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="9 18 15 12 9 6"/></svg></div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Expenses;
